/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Managers.CoberturaManager;
import Managers.MontoManager;
import Managers.ObraSocialManager;
import Managers.PrestacionManager;
import Managers.ProfesionalManager;
import Objetos.Cobertura;
import Objetos.Monto;
import Objetos.ObraSocial;
import Objetos.Profesional;
import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;
import Utils.TableGenerator.CoberturaTableGenerator;
import Utils.TableGenerator.ProfesionalTableGenerator;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class ActualizarPreciosOS extends Panel {
    
    
    private static ActualizarPreciosOS actualizarPreciosOS;

    public static ActualizarPreciosOS getInstance(){
        if(actualizarPreciosOS==null){
            actualizarPreciosOS= new ActualizarPreciosOS();
        }
        return actualizarPreciosOS;
    }
    /**
     * Creates new form ActualizarPreciosOS
     */
    private ActualizarPreciosOS() {
        initComponents();
        
        //carga de combobox
        List<ObraSocial> allObraSocial = ObraSocialManager.getInstance().getAll();
        for (ObraSocial obrasocial: allObraSocial){
            ObraSocialCB.addItem(obrasocial.getNombre());
        }
        
        //actualizacion de tabla
        ObraSocialCB.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                DefaultTableModel tableModel = (DefaultTableModel) obraSocialJT.getModel();
                tableModel.setRowCount(0); // Elimina todos los datos de la tabla

                // Agrega nuevos datos a la tabla según la opción seleccionada en el JComboBox
                String selectedOption = ObraSocialCB.getSelectedItem().toString();
                ObraSocial aux = new ObraSocial();
                aux.setNombre(selectedOption);
                ObraSocial obrasocial = ObraSocialManager.getInstance().getByName(aux);
                
                JTable auxTable = CoberturaTableGenerator.getInstance().generateTable(obrasocial);
                obraSocialJT.setModel(auxTable.getModel());
            }
        });
        
        leerTablaOS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObraSocialCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        obraSocialJT = new javax.swing.JTable();
        volverButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        ObraSocialCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion" }));
        ObraSocialCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ObraSocialCBMousePressed(evt);
            }
        });

        obraSocialJT.setBackground(new java.awt.Color(223, 246, 255));
        obraSocialJT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        obraSocialJT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                obraSocialJTKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(obraSocialJT);

        volverButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volverButton.setText("Volver");
        volverButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        volverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(ObraSocialCB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(ObraSocialCB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ObraSocialCBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObraSocialCBMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObraSocialCBMousePressed

    private void volverButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseEntered
        volverButton.setOpaque(true);
        volverButton.setBackground(new Color (150, 231, 255) );
    }//GEN-LAST:event_volverButtonMouseEntered

    private void volverButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseExited
        volverButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_volverButtonMouseExited

    private void volverButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.actualizarPrecios,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
    }//GEN-LAST:event_volverButtonMousePressed

    private void obraSocialJTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_obraSocialJTKeyTyped
        
    }//GEN-LAST:event_obraSocialJTKeyTyped
    
    private void leerTablaOS(){
        obraSocialJT.setDefaultEditor(Object.class, new DefaultCellEditor(new JTextField()) {
    {
        getComponent().addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyChar() == '\n') {
                    
                    int filaSeleccionada = obraSocialJT.getEditingRow();
            
                    if (filaSeleccionada != -1) { 
                    // Verifica si se ha seleccionado una fila
                    DefaultTableModel modelo = (DefaultTableModel) obraSocialJT.getModel();

                    // Obtén los valores de la fila seleccionada
                    String porcentajeStr = modelo.getValueAt(filaSeleccionada, 1).toString();
                    String prestacion = modelo.getValueAt(filaSeleccionada, 0).toString();
                    String topeStr = modelo.getValueAt(filaSeleccionada, 2).toString();
                    String codigo = modelo.getValueAt(filaSeleccionada, 3).toString();

                    //Control con E.R
                    String regex1 = "^(0|[1-9]\\d?|100)$";
                    String regex2 = "^[1-9]\\d*$";


                    if (porcentajeStr.matches(regex1)) {
                        int porcentaje = Integer.parseInt(porcentajeStr);

                        if(topeStr.matches(regex2)){
                            int tope = Integer.parseInt(topeStr);

                            Cobertura cobertura = new Cobertura();
                            Cobertura aux = new Cobertura();

                            aux.setCodigo(codigo);
                            aux.setTope(tope);
                            aux.setPorcentaje(porcentaje);
                            ObraSocial os = new ObraSocial();
                            os.setNombre(ObraSocialCB.getSelectedItem().toString());
                            os = ObraSocialManager.getInstance().getByName(os);
                            aux.setIdObraSocial(os.getId());
                            cobertura.setIdObraSocial(os.getId());
                            aux.setIdPrestacion(PrestacionManager.getInstance().idByName(prestacion).getId());


                            boolean result = CoberturaManager.getInstance().modify(cobertura, aux);
                            if(result){
                                DefaultTableModel tableModel = (DefaultTableModel) obraSocialJT.getModel();
                                tableModel.setRowCount(0); // Elimina todos los datos de la tabla

                                // Agrega nuevos datos a la tabla según la opción seleccionada en el JComboBox

                                String selectedOption = ObraSocialCB.getSelectedItem().toString();
                                ObraSocial a = new ObraSocial();
                                a.setNombre(selectedOption);
                                ObraSocial obrasocial = ObraSocialManager.getInstance().getByName(a);

                                JTable auxTable = CoberturaTableGenerator.getInstance().generateTable(obrasocial);
                                obraSocialJT.setModel(auxTable.getModel());
                                
                            }else{
                                JOptionPane.showMessageDialog(null, "Ocurrio un error intentando modificar la cobertura.");
                            }
                        

                    }else{
                        JOptionPane.showMessageDialog(null, "El Tope introducido es incorrecto.\n Debe ser un numero entero mayor o igual a 0.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El porcentaje introducido es incorrecto.\n Debe ser un numero entero mayor o igual a 0 y menor o igual a 100.");
                }
                    
                    }
                    
                }
            }
        });
    }
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ObraSocialCB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable obraSocialJT;
    private javax.swing.JLabel volverButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(List<Object> arguments) {
        
    }
}
