/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Managers.ObraSocialManager;
import Managers.ProfesionalManager;
import Objetos.ObraSocial;
import Objetos.Profesional;
import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;
import Utils.TableGenerator.CoberturaTableGenerator;
import Utils.TableGenerator.ProfesionalTableGenerator;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class ActualizarPreciosOS extends Panel {
    
    
    private static ActualizarPreciosOS actualizarPreciosOS;

    public static ActualizarPreciosOS getInstance(){
        if(actualizarPreciosOS==null){
            actualizarPreciosOS= new ActualizarPreciosOS();
        }
        return actualizarPreciosOS;
    }
    /**
     * Creates new form ActualizarPreciosOS
     */
    private ActualizarPreciosOS() {
        initComponents();
        
        //carga de combobox
        List<ObraSocial> allObraSocial = ObraSocialManager.getInstance().getAll();
        for (ObraSocial obrasocial: allObraSocial){
            ObraSocialCB.addItem(obrasocial.getNombre());
        }
        
        //actualizacion de tabla
        ObraSocialCB.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                DefaultTableModel tableModel = (DefaultTableModel) obraSocialJT.getModel();
                tableModel.setRowCount(0); // Elimina todos los datos de la tabla

                // Agrega nuevos datos a la tabla según la opción seleccionada en el JComboBox
                String selectedOption = ObraSocialCB.getSelectedItem().toString();
                ObraSocial aux = new ObraSocial();
                aux.setNombre(selectedOption);
                ObraSocial obrasocial = ObraSocialManager.getInstance().getByName(aux);
                
                JTable auxTable = CoberturaTableGenerator.getInstance().generateTable(obrasocial);
                obraSocialJT.setModel(auxTable.getModel());
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObraSocialCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        obraSocialJT = new javax.swing.JTable();
        volverButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        ObraSocialCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion" }));
        ObraSocialCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ObraSocialCBMousePressed(evt);
            }
        });

        obraSocialJT.setBackground(new java.awt.Color(223, 246, 255));
        obraSocialJT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(obraSocialJT);

        volverButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volverButton.setText("Volver");
        volverButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        volverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(ObraSocialCB, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(ObraSocialCB, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ObraSocialCBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObraSocialCBMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObraSocialCBMousePressed

    private void volverButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseEntered
        volverButton.setOpaque(true);
        volverButton.setBackground(new Color (150, 231, 255) );
    }//GEN-LAST:event_volverButtonMouseEntered

    private void volverButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseExited
        volverButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_volverButtonMouseExited

    private void volverButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.actualizarPrecios,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
    }//GEN-LAST:event_volverButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ObraSocialCB;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable obraSocialJT;
    private javax.swing.JLabel volverButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(List<Object> arguments) {
        
    }
}
