/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author Juan
 */
public class ActualizarPreciosPanel extends Panel {
    
    
    private static ActualizarPreciosPanel actualizarPreciosPanel;

    public static ActualizarPreciosPanel getInstance(){
        if(actualizarPreciosPanel==null){
            actualizarPreciosPanel= new ActualizarPreciosPanel();
        }
        return actualizarPreciosPanel;
    }
    
    /**
     * Creates new form ActualizarPreciosPanel
     */
    private ActualizarPreciosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        actualizarProfesionalButton = new javax.swing.JLabel();
        actualizarObraSocialButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        JLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel1.setText("Seleccione una opcion");

        actualizarProfesionalButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualizarProfesionalButton.setText("Actualizar Lista de Precios Profesional");
        actualizarProfesionalButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        actualizarProfesionalButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        actualizarProfesionalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actualizarProfesionalButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizarProfesionalButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actualizarProfesionalButtonMousePressed(evt);
            }
        });

        actualizarObraSocialButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualizarObraSocialButton.setText("Actualizar Lista de Precios Obras Sociales");
        actualizarObraSocialButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        actualizarObraSocialButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        actualizarObraSocialButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                actualizarObraSocialButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                actualizarObraSocialButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                actualizarObraSocialButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(actualizarProfesionalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(actualizarObraSocialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(JLabel1)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(JLabel1)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarObraSocialButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizarProfesionalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(398, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarProfesionalButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarProfesionalButtonMouseEntered
        actualizarProfesionalButton.setOpaque(true);
        actualizarProfesionalButton.setBackground(new Color (150, 231, 255) );
    }//GEN-LAST:event_actualizarProfesionalButtonMouseEntered

    private void actualizarProfesionalButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarProfesionalButtonMouseExited
        actualizarProfesionalButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_actualizarProfesionalButtonMouseExited

    private void actualizarProfesionalButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarProfesionalButtonMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.actualizarPreciosProfesional,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
        actualizarProfesionalButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_actualizarProfesionalButtonMousePressed

    private void actualizarObraSocialButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarObraSocialButtonMouseEntered
        actualizarObraSocialButton.setOpaque(true);
        actualizarObraSocialButton.setBackground(new Color (150, 231, 255) );
    }//GEN-LAST:event_actualizarObraSocialButtonMouseEntered

    private void actualizarObraSocialButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarObraSocialButtonMouseExited
        actualizarObraSocialButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_actualizarObraSocialButtonMouseExited

    private void actualizarObraSocialButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualizarObraSocialButtonMousePressed
        // TODO add your handling code here:
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.actualizaros,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
        actualizarObraSocialButton.setBackground(new Color (223, 246, 255));
    }//GEN-LAST:event_actualizarObraSocialButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel actualizarObraSocialButton;
    private javax.swing.JLabel actualizarProfesionalButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(List<Object> arguments) {
    }
}
