/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Managers.TurnoManager;
import Objetos.Profesional;
import Objetos.Turno;
import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;
import Utils.String2Date;
import java.awt.Color;

import javax.swing.*;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author franc
 */
public class EliminarTurno extends Panel {

    private TableColumn idsTurnos;

    private static EliminarTurno eliminarTurno;

    public static EliminarTurno getInstance(){
        if(eliminarTurno==null){
            eliminarTurno=new EliminarTurno();
        }
        return eliminarTurno;
    }

    /**
     * Creates new form EliminarTurno
     */
    private EliminarTurno() {
        initComponents();
    }

    @Override
    public void setup(List<Object> arguments) {
        jTextField1.setText("");
        JTable auxTable = TurnoManager.getInstance().getFuturePatientAppointments(-1);
        turnosTable.setModel(auxTable.getModel());
        this.removeColumn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        buscarButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        turnosTable = new javax.swing.JTable();
        cancelarButton = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        jLabel1.setText("Ingrese el documento del paciente");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buscarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarButton.setText("Buscar");
        buscarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        buscarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarButtonMousePressed(evt);
            }
        });

        turnosTable.setBackground(new java.awt.Color(223, 244, 255));
        turnosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(turnosTable);

        cancelarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelarButton.setText("Cancelar");
        cancelarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarButtonMousePressed(evt);
            }
        });

        confirmarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        confirmarButton.setText("Confirmar");
        confirmarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        confirmarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmarButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarButtonMousePressed(evt);
            }
        });

        jLabel2.setText("Eliminar turno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(27, 27, 27)
                .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(403, 403, 403))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buscarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonMousePressed
        String dniString = jTextField1.getText().trim();
        String errorString = "";
        boolean error = false;
        Pattern patron = Pattern.compile("^[1-9]\\d{6,9}$");
        Matcher matcher1 = patron.matcher(dniString);
        if (matcher1.matches()){
            JTable auxTable = TurnoManager.getInstance().getFuturePatientAppointments(Long.parseLong(dniString));
            turnosTable.setModel(auxTable.getModel());
            this.removeColumn();
            if(turnosTable.getRowCount()==0){
                error = true;
                errorString = errorString + "No existe un turno futuro para ese paciente \n";
            }
        } else {
            error = true;
            jTextField1.setText("");
            errorString = errorString + "DNI Ingresado invalido \n";
        }
        if (error){
            JOptionPane.showMessageDialog(null, "Error!\n" + errorString);
        }



    }//GEN-LAST:event_buscarButtonMousePressed

    private void confirmarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarButtonMousePressed
        Object[] options = {"Sí", "No"};

        String[] optionsStr = new String[options.length];
        for (int i = 0; i < options.length; i++) {
            optionsStr[i] = options[i].toString();
        }

        int resp = JOptionPane.showOptionDialog(this,
                "Usted esta a punto de eliminar el turno.\n"+"¿Esta seguro?",
                "Alerta!",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                optionsStr,
                optionsStr[1]);

        if(resp == 0){
            // code for yes response
            int row = turnosTable.getSelectedRow();
            turnosTable.addColumn(idsTurnos);
            Turno turno = TurnoManager.getInstance().getById(Integer.parseInt(turnosTable.getValueAt(row,5).toString()));
            turnosTable.removeColumn(idsTurnos);
            TurnoManager.getInstance().deleteTurno(turno);
            confirmarButton.setBackground(new Color (223, 246, 255) );
            PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.panelTurnos,null);
            SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
        }else{
            //code respuesta no
        }

    }//GEN-LAST:event_confirmarButtonMousePressed

    private void cancelarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMousePressed
        cancelarButton.setBackground(new Color (223, 246, 255) );
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.panelTurnos,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
    }//GEN-LAST:event_cancelarButtonMousePressed

    private void cancelarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseEntered
        cancelarButton.setOpaque(true);
        cancelarButton.setBackground(new Color (255, 105, 97) ); 
    }//GEN-LAST:event_cancelarButtonMouseEntered

    private void cancelarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseExited
         cancelarButton.setBackground(new Color (223, 246, 255) );  
    }//GEN-LAST:event_cancelarButtonMouseExited

    private void buscarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonMouseEntered
        buscarButton.setOpaque(true);
        buscarButton.setBackground(new Color (150, 231, 255) ); 
    }//GEN-LAST:event_buscarButtonMouseEntered

    private void buscarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarButtonMouseExited
        buscarButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_buscarButtonMouseExited

    private void confirmarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarButtonMouseEntered
        confirmarButton.setOpaque(true);
        confirmarButton.setBackground(new Color (152, 251, 152) ); 
    }//GEN-LAST:event_confirmarButtonMouseEntered

    private void confirmarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarButtonMouseExited
        confirmarButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_confirmarButtonMouseExited

    private void removeColumn(){
        DefaultTableColumnModel tcm = (DefaultTableColumnModel)turnosTable.getColumnModel();
        idsTurnos = tcm.getColumn(5);
        tcm.removeColumn(tcm.getColumn(5));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarButton;
    private javax.swing.JLabel cancelarButton;
    private javax.swing.JLabel confirmarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable turnosTable;
    // End of variables declaration//GEN-END:variables
}
