/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Managers.EstadisticasManager;
import Objetos.Gasto;
import Objetos.Ingreso;
import Objetos.Profesional;
import Objetos.Turno;
import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author joako
 */
public class EstadisticasProfesionalPanel extends Panel {
    private static EstadisticasProfesionalPanel estadisticas;
    private List<Profesional> profesionalList;
    public static EstadisticasProfesionalPanel getInstance(){
        if(estadisticas == null){
            estadisticas = new EstadisticasProfesionalPanel();
        }
        return estadisticas;
    }
    /**
     * Creates new form EstadisticasProfesionalPanel
     */
    public EstadisticasProfesionalPanel() {
        initComponents();
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        tALabel.setVisible(false);
        turnosNoAsistidosLabel.setVisible(false);
        cantidadDeIngresosLabel.setVisible(false);
        cantidadDeGastosLabel.setVisible(false);
        saldoLabel.setVisible(false);
        tALabel30.setVisible(false);
        turnosNoAsistidos30Label.setVisible(false);
        cantidadDeIngresos30Label.setVisible(false);
        cantidadDeGastos30Label.setVisible(false);
        saldo30Label.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tALabel = new javax.swing.JLabel();
        turnosNoAsistidosLabel = new javax.swing.JLabel();
        cantidadDeIngresosLabel = new javax.swing.JLabel();
        cantidadDeGastosLabel = new javax.swing.JLabel();
        saldoLabel = new javax.swing.JLabel();
        tALabel30 = new javax.swing.JLabel();
        turnosNoAsistidos30Label = new javax.swing.JLabel();
        cantidadDeIngresos30Label = new javax.swing.JLabel();
        cantidadDeGastos30Label = new javax.swing.JLabel();
        saldo30Label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estadisticasProCB = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        JLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel1.setText("Elija un profesional");

        jLabel1.setText("Turnos atendidos:");

        jLabel2.setText("Turnos que no asistieron:");

        jLabel3.setText("Cantidad de ingresos:");

        jLabel4.setText("Cantidad de gastos:");

        jLabel5.setText("Saldo:");

        tALabel.setText("jLabel6");

        turnosNoAsistidosLabel.setText("jLabel6");

        cantidadDeIngresosLabel.setText("jLabel6");

        cantidadDeGastosLabel.setText("jLabel6");

        saldoLabel.setText("jLabel6");

        tALabel30.setText("jLabel6");

        turnosNoAsistidos30Label.setText("jLabel6");

        cantidadDeIngresos30Label.setText("jLabel6");

        cantidadDeGastos30Label.setText("jLabel6");

        saldo30Label.setText("jLabel6");

        jLabel6.setText("Turnos atendidos:");

        jLabel7.setText("Turnos que no asistieron:");

        jLabel8.setText("Cantidad de ingresos:");

        jLabel9.setText("Cantidad de gastos:");

        jLabel10.setText("Saldo:");

        estadisticasProCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", " " }));
        estadisticasProCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasProCBActionPerformed(evt);
            }
        });

        jLabel11.setText("Ultimos 30 dias");

        jLabel12.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tALabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(turnosNoAsistidosLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cantidadDeIngresosLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cantidadDeGastosLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(saldoLabel))
                            .addComponent(jLabel12))
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(turnosNoAsistidos30Label))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cantidadDeIngresos30Label))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(saldo30Label))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cantidadDeGastos30Label))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(tALabel30))))
                    .addComponent(estadisticasProCB, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(JLabel1)
                .addGap(18, 18, 18)
                .addComponent(estadisticasProCB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tALabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnosNoAsistidosLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadDeIngresosLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadDeGastosLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saldoLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tALabel30))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnosNoAsistidos30Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadDeIngresos30Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadDeGastos30Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saldo30Label))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void estadisticasProCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasProCBActionPerformed
        Profesional profesional = null;

        if(estadisticasProCB.getSelectedIndex()==0){
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            tALabel.setVisible(false);
            turnosNoAsistidosLabel.setVisible(false);
            cantidadDeIngresosLabel.setVisible(false);
            cantidadDeGastosLabel.setVisible(false);
            saldoLabel.setVisible(false);
            tALabel30.setVisible(false);
            turnosNoAsistidos30Label.setVisible(false);
            cantidadDeIngresos30Label.setVisible(false);
            cantidadDeGastos30Label.setVisible(false);
            saldo30Label.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel1.setVisible(false);
            jLabel12.setVisible(false);
            jLabel11.setVisible(false);
        }
        else{
            profesional = profesionalList.get(estadisticasProCB.getSelectedIndex()-1);
            Turno turno = new Turno();
            turno.setIdProfesional(profesional.getId());
            Ingreso ingreso = new Ingreso();
            Gasto gasto = new Gasto();
            ingreso.setIdProfesional(profesional.getId());
            gasto.setIdProfesional(profesional.getId());

            List<Integer> turnos = new ArrayList<>();
            List<Float> ingrGasto = new ArrayList<>();

            turnos = EstadisticasManager.getInstance().getAssistedTurnos(turno);
            ingrGasto = EstadisticasManager.getInstance().getIngresoGastoByProfesional(ingreso, gasto);

            jLabel1.setVisible(true);
            jLabel12.setVisible(true);
            jLabel11.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            tALabel.setText(turnos.get(0).toString());
            tALabel.setVisible(true);

            turnosNoAsistidosLabel.setVisible(true);
            turnosNoAsistidosLabel.setText(turnos.get(1).toString());

            cantidadDeIngresosLabel.setText(ingrGasto.get(0).toString());
            cantidadDeIngresosLabel.setVisible(true);

            cantidadDeGastosLabel.setText(ingrGasto.get(1).toString());
            cantidadDeGastosLabel.setVisible(true);

            saldoLabel.setText(String.valueOf(ingrGasto.get(0)-ingrGasto.get(1)));
            saldoLabel.setVisible(true);

            tALabel30.setText(turnos.get(2).toString());
            tALabel30.setVisible(true);

            turnosNoAsistidos30Label.setText(turnos.get(3).toString());
            turnosNoAsistidos30Label.setVisible(true);

            cantidadDeIngresos30Label.setText(ingrGasto.get(2).toString());
            cantidadDeIngresos30Label.setVisible(true);

            cantidadDeGastos30Label.setText(ingrGasto.get(3).toString());
            cantidadDeGastos30Label.setVisible(true);

            saldo30Label.setText(String.valueOf(ingrGasto.get(2)-ingrGasto.get(3)));
            saldo30Label.setVisible(true);

            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
        }


    }//GEN-LAST:event_estadisticasProCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel cantidadDeGastos30Label;
    private javax.swing.JLabel cantidadDeGastosLabel;
    private javax.swing.JLabel cantidadDeIngresos30Label;
    private javax.swing.JLabel cantidadDeIngresosLabel;
    private javax.swing.JComboBox<String> estadisticasProCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel saldo30Label;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JLabel tALabel;
    private javax.swing.JLabel tALabel30;
    private javax.swing.JLabel turnosNoAsistidos30Label;
    private javax.swing.JLabel turnosNoAsistidosLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(List<Object> arguments) {
        profesionalList = EstadisticasManager.getInstance().getAllProfesional();
        ComboBoxModel<String> cb = new DefaultComboBoxModel<>();
        estadisticasProCB.setModel(cb);
        estadisticasProCB.addItem("Ingrese una opcion");
        for (int i=1;i<=profesionalList.size();i++) {
            estadisticasProCB.insertItemAt(profesionalList.get(i-1).getNombre(),i);
        }
    }
}
