/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;

import java.util.List;

/**
 *
 * @author franc
 */
public class FinanzasPanel extends Panel {

    private static FinanzasPanel finanzasPanel;

    public static FinanzasPanel getInstance(){
        if(finanzasPanel==null){
            finanzasPanel= new FinanzasPanel();
        }
        return finanzasPanel;
    }
    

    /**
     * Creates new form FinanzasPanel
     */
    private FinanzasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarGastoButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        agregarGastoButton.setText("Agregar Gasto");
        agregarGastoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarGastoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarGastoButtonMousePressed(evt);
            }
        });

        jLabel2.setText("Agregar Ingreso");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(agregarGastoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(263, 263, 263))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarGastoButton)
                    .addComponent(jLabel2))
                .addContainerGap(349, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarGastoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarGastoButtonMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.agregarGasto,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioFinanzas,null);
        
    }//GEN-LAST:event_agregarGastoButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarGastoButton;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(List<Object> arguments) {
        
    }
}
