/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;
import java.awt.Color;

import java.util.List;

/**
 *
 * @author franc
 */
public class FinanzasPanel extends Panel {

    private static FinanzasPanel finanzasPanel;

    public static FinanzasPanel getInstance(){
        if(finanzasPanel==null){
            finanzasPanel= new FinanzasPanel();
        }
        return finanzasPanel;
    }
    

    /**
     * Creates new form FinanzasPanel
     */
    private FinanzasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarGastoButton = new javax.swing.JLabel();
        agregarIngresoButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        agregarGastoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarGastoButton.setText("Agregar Gasto");
        agregarGastoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregarGastoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarGastoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarGastoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarGastoButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarGastoButtonMousePressed(evt);
            }
        });

        agregarIngresoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarIngresoButton.setText("Agregar Ingreso");
        agregarIngresoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregarIngresoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregarIngresoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarIngresoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarIngresoButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(agregarGastoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(agregarIngresoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarGastoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarIngresoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarGastoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarGastoButtonMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.agregarGasto,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioFinanzas,null);
        
    }//GEN-LAST:event_agregarGastoButtonMousePressed

    private void agregarGastoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarGastoButtonMouseEntered
       agregarGastoButton.setOpaque(true);
        agregarGastoButton.setBackground(new Color (150, 231, 255) ); 
    }//GEN-LAST:event_agregarGastoButtonMouseEntered

    private void agregarGastoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarGastoButtonMouseExited
        agregarGastoButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_agregarGastoButtonMouseExited

    private void agregarIngresoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarIngresoButtonMouseEntered
        agregarIngresoButton.setOpaque(true);
        agregarIngresoButton.setBackground(new Color (150, 231, 255) ); 
    }//GEN-LAST:event_agregarIngresoButtonMouseEntered

    private void agregarIngresoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarIngresoButtonMouseExited
        agregarIngresoButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_agregarIngresoButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarGastoButton;
    private javax.swing.JLabel agregarIngresoButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(List<Object> arguments) {
        
    }
}
