/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Managers.IngresoManager;
import Objetos.ObraSocial;
import Objetos.Paciente;
import Objetos.Profesional;
import Objetos.Turno;
import Utils.FormatedDate;
import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;
import org.jdatepicker.impl.DateComponentFormatter;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

import javax.swing.*;
import java.util.Date;
import java.util.List;
import java.util.Properties;

/**
 *
 * @author franc
 */
public class IngresoPanel extends Panel {

    private Turno turno;
    private Profesional pr;

    private  Paciente p;
    private JDatePickerImpl datePicker;
    private JDatePanelImpl datePanel;

    private UtilDateModel model;

    private List<ObraSocial> obraSocialList;

    @Override
    public void setup(List<Object> arguments) {
        turno = (Turno)arguments.get(0);
        pr = IngresoManager.getInstance().getProfesionalById(turno.getIdProfesional());
        p = IngresoManager.getInstance().getPacienteById(turno.getIdPaciente());
        profesionalLabel.setText(pr.getNombre());
        pacienteLabel.setText(p.getNombre());
        Date today = FormatedDate.formatedDate(new Date());
        model.setDate(today.getYear()+1900, today.getMonth(),today.getDay());
        model.setSelected(true);
        obraSocialList=IngresoManager.getInstance().getObraSocialByIdPaciente(p.getId());
        for (ObraSocial obraSocial: obraSocialList){
            jComboBox1.addItem(obraSocial.getNombre());
        }
    }
    private static IngresoPanel ingresoPanel;

    public static IngresoPanel getInstance(){
        if (ingresoPanel==null){
            ingresoPanel = new IngresoPanel();
        }
        return ingresoPanel;
    }


    /**
     * Creates new form IngresoPanel
     */
    private IngresoPanel() {
        initComponents();
        model= new UtilDateModel();
        //IMPORTANTE a partir de la version 1.3.4 de JDatePicker se necesita darle properties al DatePanel
        // link: https://stackoverflow.com/questions/26794698/how-do-i-implement-jdatepicker
        Properties p = new Properties();
        p.put("text.today", "Today");
        p.put("text.month", "Month");
        p.put("text.year", "Year");
        Date today = FormatedDate.formatedDate(new Date());
        model.setDate(today.getYear()+1900, today.getMonth(),today.getDay());
        datePanel=new JDatePanelImpl(model,p);
        datePicker = new JDatePickerImpl(datePanel, new DateComponentFormatter());
        datePickerPanel.add(datePicker);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        profesionalLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pacienteLabel = new javax.swing.JLabel();
        datePickerPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        montoTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        confirmarButton = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(223, 246, 255));
        setPreferredSize(new java.awt.Dimension(907, 652));

        jLabel1.setText("Profesional:");

        profesionalLabel.setText("aca va el profesional");

        jLabel2.setText("Paciente");

        pacienteLabel.setText("aca va el Paciente");

        datePickerPanel.setBackground(new java.awt.Color(223, 246, 255));
        datePickerPanel.setLayout(new java.awt.CardLayout());

        jLabel3.setText("Fecha:");

        jLabel4.setText("Monto:");

        jLabel5.setText("Descripcion:");

        jScrollPane1.setBackground(new java.awt.Color(223, 244, 255));

        jTextArea1.setBackground(new java.awt.Color(234, 244, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        confirmarButton.setText("Confirmar");
        confirmarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarButtonMousePressed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelarButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarButtonMousePressed(evt);
            }
        });

        jLabel6.setText("ObraSocial:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Ninguna" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(pacienteLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(profesionalLabel)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(168, 168, 168)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(montoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(datePickerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(cancelarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmarButton)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profesionalLabel)
                    .addComponent(datePickerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(pacienteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(montoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarButton)
                    .addComponent(cancelarButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarButtonMousePressed
        boolean error = false;
        String errStr = "";
        float monto =0;
        String descripcion = jTextArea1.getText();
        Date auxFecha = FormatedDate.formatedDate((Date) datePicker.getModel().getValue());
        java.sql.Date fecha = new java.sql.Date(auxFecha.getTime());
        if (montoTF.getText().isBlank()){
            error = true;
            errStr = errStr+"\n Ingrese un numero";
        }
        else {
            try {
                monto=Float.parseFloat(montoTF.getText());
            }
            catch (NumberFormatException e){
                error= true;
                errStr=errStr+"\n Ingrese un numero";
            }
        }
        if(jComboBox1.getSelectedIndex() ==0){
            error = true;
            errStr = errStr+"\n Seleccione una obra social";
        }
        if(error){
            JOptionPane.showMessageDialog(null, "Error!\n" + errStr);
        }
        else {
            ObraSocial obraSocial = null;
            if(jComboBox1.getSelectedIndex()!=1){
                 obraSocial = obraSocialList.get(jComboBox1.getSelectedIndex()-2);
            }
            else {
                obraSocial = new ObraSocial();
                obraSocial.setId(-1);
            }
            IngresoManager.getInstance().add(fecha,p.getId(),pr.getId(),turno.getId(),obraSocial.getId(),monto, descripcion);
            PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.finanzas,null);
            SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
        }




    }//GEN-LAST:event_confirmarButtonMousePressed

    private void cancelarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarButtonMouseExited

    private void cancelarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.finanzas,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
    }//GEN-LAST:event_cancelarButtonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelarButton;
    private javax.swing.JLabel confirmarButton;
    private javax.swing.JPanel datePickerPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField montoTF;
    private javax.swing.JLabel pacienteLabel;
    private javax.swing.JLabel profesionalLabel;
    // End of variables declaration//GEN-END:variables
}
