/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;

import java.util.List;

/**
 *
 * @author franc
 */
public class MenuSecundarioFinanzas extends Panel {

    private static MenuSecundarioFinanzas menuSecundarioFinanzas;

    public static MenuSecundarioFinanzas getInstance(){
        if(menuSecundarioFinanzas==null){
            menuSecundarioFinanzas= new MenuSecundarioFinanzas();
        }
        return menuSecundarioFinanzas;
    }

    /**
     * Creates new form menuSecundarioFinanzas
     */
    private MenuSecundarioFinanzas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarGastoButton = new javax.swing.JLabel();
        agregarIngresoButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(78, 217, 255));

        agregarGastoButton.setText("Agregar Gasto");
        agregarGastoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarGastoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarGastoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarGastoButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarGastoButtonMousePressed(evt);
            }
        });

        agregarIngresoButton.setText("Agregar Ingreso");
        agregarIngresoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarIngresoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarIngresoButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarIngresoButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(agregarGastoButton)
                .addGap(196, 196, 196)
                .addComponent(agregarIngresoButton)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarGastoButton)
                    .addComponent(agregarIngresoButton))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarGastoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarGastoButtonMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.agregarGasto,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioFinanzas,null);
    }//GEN-LAST:event_agregarGastoButtonMousePressed

    private void agregarIngresoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarIngresoButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarIngresoButtonMousePressed

    private void agregarIngresoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarIngresoButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarIngresoButtonMouseEntered

    private void agregarIngresoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarIngresoButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarIngresoButtonMouseExited

    private void agregarGastoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarGastoButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarGastoButtonMouseEntered

    private void agregarGastoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarGastoButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarGastoButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarGastoButton;
    private javax.swing.JLabel agregarIngresoButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setup(List<Object> arguments) {
        
    }
}
