/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Utils.GUIUtils.PanelGUIHandler;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author franc
 */
public class MenuSecundarioTurnos extends Panel {

    private static MenuSecundarioTurnos menuSecundarioTurnos;

    public static MenuSecundarioTurnos getInstance(){
        if(menuSecundarioTurnos==null){
            menuSecundarioTurnos=new MenuSecundarioTurnos();
        }
        return menuSecundarioTurnos;
    }

    /**
     * Creates new form MenuSecundarioTurnos
     */
    private MenuSecundarioTurnos() {
        initComponents();
    }

    @Override
    public void setup(List<Object> arguments) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarTurno = new javax.swing.JLabel();
        modificarTurno = new javax.swing.JLabel();
        eliminarTurno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(78, 217, 255));

        agregarTurno.setText("Agregar Turno");
        agregarTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarTurnoMousePressed(evt);
            }
        });

        modificarTurno.setText("Modificar Turno");
        modificarTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarTurnoMousePressed(evt);
            }
        });

        eliminarTurno.setText("Elminar Turno");
        eliminarTurno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarTurnoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(agregarTurno)
                .addGap(186, 186, 186)
                .addComponent(modificarTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(eliminarTurno)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarTurno)
                    .addComponent(modificarTurno)
                    .addComponent(eliminarTurno))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarTurnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarTurnoMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.agregarTurno,null);
    }//GEN-LAST:event_agregarTurnoMousePressed

    private void modificarTurnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarTurnoMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.modificarTurno,null);
    }//GEN-LAST:event_modificarTurnoMousePressed

    private void eliminarTurnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTurnoMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.eliminarTurno,null);
    }//GEN-LAST:event_eliminarTurnoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agregarTurno;
    private javax.swing.JLabel eliminarTurno;
    private javax.swing.JLabel modificarTurno;
    // End of variables declaration//GEN-END:variables
}
