/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;
import Utils.TableGenerator.CalendarTableGenerator;
import org.jdatepicker.impl.DateComponentFormatter;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;


import java.util.List;
import java.util.Properties;

/**
 *
 * @author franc
 */
public class MenuModificarTurno extends Panel {


    //IMPORTANTE datepicker necesita un datepanel, que necesita un datemodel, la inicializacion de los mismos esta en el constructor
    // link de instruccion : https://www.codejava.net/java-se/swing/how-to-use-jdatepicker-to-display-calendar-component
    private JDatePickerImpl datePicker;
    private JDatePanelImpl datePanel;
    private UtilDateModel model;
    
    

    private static MenuModificarTurno modificarTurno;

    public static MenuModificarTurno getInstance(){
        if(modificarTurno==null){
            modificarTurno=new MenuModificarTurno();
        }
        return modificarTurno;
    }
    
    

    /**
     * Creates new form ModificarTurno
     */
    private MenuModificarTurno() {
        initComponents();


        model= new UtilDateModel();

        //IMPORTANTE a partir de la version 1.3.4 de JDatePicker se necesita darle properties al DatePanel
        // link: https://stackoverflow.com/questions/26794698/how-do-i-implement-jdatepicker
        Properties p = new Properties();
        p.put("text.today", "Today");
        p.put("text.month", "Month");
        p.put("text.year", "Year");
        datePanel=new JDatePanelImpl(model,p);
        datePicker = new JDatePickerImpl(datePanel, new DateComponentFormatter());
        datePickerPanel.add(datePicker);
    }



    @Override
    public void setup(List<Object> arguments) {
        calendarTable.setModel(CalendarTableGenerator.getInstance().resultToTable());



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        calendarTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horaInicioTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        horaFinTF = new javax.swing.JTextField();
        configurarPrestacionesButton = new javax.swing.JLabel();
        profesionalLabel = new javax.swing.JLabel();
        pacienteLabel = new javax.swing.JLabel();
        flechaIzqButton = new javax.swing.JLabel();
        cancelarButton = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JLabel();
        flechaDerechaButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precioLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        descuentoTF = new javax.swing.JTextField();
        asistioCheckBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        datePickerPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(223, 246, 255));

        calendarTable.setBackground(new java.awt.Color(223, 244, 255));
        calendarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(calendarTable);

        jLabel1.setText("Profesional: ");

        jLabel2.setText("Paciente:");

        jLabel6.setText("Fecha: ");

        jLabel4.setText("Hora de inicio:");

        jLabel5.setText("Hora de fin:");

        configurarPrestacionesButton.setText("Configurar prestaciones");
        configurarPrestacionesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configurarPrestacionesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                configurarPrestacionesButtonMousePressed(evt);
            }
        });

        profesionalLabel.setText("Profesional");

        pacienteLabel.setText("Paciente");

        flechaIzqButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left-arrow 24x24.png"))); // NOI18N
        flechaIzqButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flechaIzqButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                flechaIzqButtonMousePressed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarButtonMousePressed(evt);
            }
        });

        confirmarButton.setText("Confirmar");
        confirmarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                confirmarButtonMousePressed(evt);
            }
        });

        flechaDerechaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/right-arrow 24x24.png"))); // NOI18N
        flechaDerechaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flechaDerechaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                flechaDerechaButtonMousePressed(evt);
            }
        });

        jLabel3.setText("Precio:");

        precioLabel.setText("precio");

        jLabel10.setText("Descuento:");

        asistioCheckBox.setText("Asistio");
        asistioCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asistioCheckBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("%");

        datePickerPanel.setBackground(new java.awt.Color(223, 246, 255));
        datePickerPanel.setPreferredSize(new java.awt.Dimension(100, 29));
        datePickerPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(profesionalLabel)
                    .addComponent(jLabel2)
                    .addComponent(asistioCheckBox)
                    .addComponent(pacienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel10))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(configurarPrestacionesButton))
                            .addComponent(datePickerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horaFinTF, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horaInicioTF, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(precioLabel)
                        .addGap(90, 90, 90)
                        .addComponent(descuentoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flechaIzqButton)
                .addGap(212, 212, 212)
                .addComponent(cancelarButton)
                .addGap(168, 168, 168)
                .addComponent(confirmarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(flechaDerechaButton)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(profesionalLabel)
                        .addComponent(horaInicioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(datePickerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(pacienteLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(configurarPrestacionesButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(horaFinTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3))))
                        .addGap(18, 18, 18)
                        .addComponent(asistioCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flechaIzqButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(flechaDerechaButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descuentoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioLabel)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelarButton)
                            .addComponent(confirmarButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configurarPrestacionesButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurarPrestacionesButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_configurarPrestacionesButtonMousePressed

    private void cancelarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarButtonMousePressed
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.panelInicio,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioVacio,null);
    }//GEN-LAST:event_cancelarButtonMousePressed

    private void confirmarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarButtonMousePressed

    }//GEN-LAST:event_confirmarButtonMousePressed

    private void flechaDerechaButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaDerechaButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_flechaDerechaButtonMousePressed

    private void flechaIzqButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaIzqButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_flechaIzqButtonMousePressed

    private void asistioCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asistioCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asistioCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asistioCheckBox;
    private javax.swing.JTable calendarTable;
    private javax.swing.JLabel cancelarButton;
    private javax.swing.JLabel configurarPrestacionesButton;
    private javax.swing.JLabel confirmarButton;
    private javax.swing.JPanel datePickerPanel;
    private javax.swing.JTextField descuentoTF;
    private javax.swing.JLabel flechaDerechaButton;
    private javax.swing.JLabel flechaIzqButton;
    private javax.swing.JTextField horaFinTF;
    private javax.swing.JTextField horaInicioTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pacienteLabel;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JLabel profesionalLabel;
    // End of variables declaration//GEN-END:variables
}
