/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import java.util.List;

/**
 *
 * @author franc
 */
public class PanelTurnos extends Panel {

    private static PanelTurnos panelTurnos;

    public static PanelTurnos getInstance(){
        if(panelTurnos==null){
            panelTurnos= new PanelTurnos();
        }
        return panelTurnos;
    }

    /**
     * Creates new form PanelTurnos
     */
    private PanelTurnos() {
        initComponents();
    }

    @Override
    public void setup(List<Object> arguments) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        agregarTurnoButton = new javax.swing.JLabel();
        modificarTurnoButton = new javax.swing.JLabel();
        eliminarTurnoButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        JLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel1.setText("Seleccione una opcion");

        agregarTurnoButton.setText("Agregar Turno");
        agregarTurnoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarTurnoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarTurnoButtonMousePressed(evt);
            }
        });

        modificarTurnoButton.setText("Modificar Turno");
        modificarTurnoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarTurnoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarTurnoButtonMousePressed(evt);
            }
        });

        eliminarTurnoButton.setText("Eliminar Turno");
        eliminarTurnoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarTurnoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarTurnoButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(agregarTurnoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(modificarTurnoButton)
                .addGap(161, 161, 161)
                .addComponent(eliminarTurnoButton)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(JLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(JLabel1)
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarTurnoButton)
                    .addComponent(modificarTurnoButton)
                    .addComponent(eliminarTurnoButton))
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarTurnoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarTurnoButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarTurnoButtonMousePressed

    private void modificarTurnoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarTurnoButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarTurnoButtonMousePressed

    private void eliminarTurnoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTurnoButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarTurnoButtonMousePressed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel agregarTurnoButton;
    private javax.swing.JLabel eliminarTurnoButton;
    private javax.swing.JLabel modificarTurnoButton;
    // End of variables declaration//GEN-END:variables
}
