/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUIComponents;

import Utils.GUIUtils.PanelGUIHandler;
import Utils.GUIUtils.SMenuGUIHandler;
import java.awt.Color;

import java.util.List;

/**
 *
 * @author franc
 */
public class PanelTurnos extends Panel {

    private static PanelTurnos panelTurnos;

    public static PanelTurnos getInstance(){
        if(panelTurnos==null){
            panelTurnos= new PanelTurnos();
        }
        return panelTurnos;
    }

    /**
     * Creates new form PanelTurnos
     */
    private PanelTurnos() {
        initComponents();
    }

    @Override
    public void setup(List<Object> arguments) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel1 = new javax.swing.JLabel();
        agregarTurnoButton = new javax.swing.JLabel();
        modificarTurnoButton = new javax.swing.JLabel();
        eliminarTurnoButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 246, 255));

        JLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JLabel1.setText("Seleccione una opcion");

        agregarTurnoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarTurnoButton.setText("Agregar Turno");
        agregarTurnoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregarTurnoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarTurnoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarTurnoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarTurnoButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregarTurnoButtonMousePressed(evt);
            }
        });

        modificarTurnoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificarTurnoButton.setText("Modificar Turno");
        modificarTurnoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        modificarTurnoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificarTurnoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificarTurnoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarTurnoButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificarTurnoButtonMousePressed(evt);
            }
        });

        eliminarTurnoButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminarTurnoButton.setText("Eliminar Turno");
        eliminarTurnoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eliminarTurnoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminarTurnoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarTurnoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarTurnoButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminarTurnoButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarTurnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(modificarTurnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(eliminarTurnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JLabel1))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(JLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarTurnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarTurnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarTurnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(530, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarTurnoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarTurnoButtonMousePressed
        agregarTurnoButton.setBackground(new Color (223, 246, 255) );
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.agregarTurno,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioTurnos,null);
    }//GEN-LAST:event_agregarTurnoButtonMousePressed

    private void modificarTurnoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarTurnoButtonMousePressed
        modificarTurnoButton.setBackground(new Color (223, 246, 255) );
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.buscarPaciente,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioTurnos,null);
    }//GEN-LAST:event_modificarTurnoButtonMousePressed

    private void eliminarTurnoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTurnoButtonMousePressed
        eliminarTurnoButton.setBackground(new Color (223, 246, 255) );
        PanelGUIHandler.getinstance().changePanel(PanelGUIHandler.eliminarTurno,null);
        SMenuGUIHandler.getInstance().changePanel(SMenuGUIHandler.menuSecundarioTurnos,null);
    }//GEN-LAST:event_eliminarTurnoButtonMousePressed

    private void agregarTurnoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarTurnoButtonMouseEntered
        agregarTurnoButton.setOpaque(true);
        agregarTurnoButton.setBackground(new Color (150, 231, 255) ); 
    }//GEN-LAST:event_agregarTurnoButtonMouseEntered

    private void agregarTurnoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarTurnoButtonMouseExited
        agregarTurnoButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_agregarTurnoButtonMouseExited

    private void modificarTurnoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarTurnoButtonMouseEntered
        modificarTurnoButton.setOpaque(true);
        modificarTurnoButton.setBackground(new Color (150, 231, 255) );
    }//GEN-LAST:event_modificarTurnoButtonMouseEntered

    private void modificarTurnoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarTurnoButtonMouseExited
       modificarTurnoButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_modificarTurnoButtonMouseExited

    private void eliminarTurnoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTurnoButtonMouseEntered
        eliminarTurnoButton.setOpaque(true);
        eliminarTurnoButton.setBackground(new Color (150, 231, 255) );
    }//GEN-LAST:event_eliminarTurnoButtonMouseEntered

    private void eliminarTurnoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarTurnoButtonMouseExited
         eliminarTurnoButton.setBackground(new Color (223, 246, 255) );
    }//GEN-LAST:event_eliminarTurnoButtonMouseExited




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JLabel agregarTurnoButton;
    private javax.swing.JLabel eliminarTurnoButton;
    private javax.swing.JLabel modificarTurnoButton;
    // End of variables declaration//GEN-END:variables
}
